#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Haruki Matsushita
# SPDX-License-Identifier: BSD-3-Clause


import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except ValueError:
        try:
            ans += float(line)
        except ValueError:
            print("Eroor")
            sys.exit(1)
            


print(ans)

if ans % 2 == 0:
    print("even number")
    print("value divided by 2:", ans/2)

else:
    print("odd number")

