#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Haruki Matsushita
# SPDX-License-Identifier: BSD-3-Clause


import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print("合計値:"+str(ans))


if ans % 2 == 0:
    print("even number")
    print("値を2で割った数:", ans/2)
else:
    print("odd number")
