#!i/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Haruki Matsushita
# SPDX-License-Identifier: BSD-3-Clause


import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)


print(ans)

if aus % 2 == 0:
    print("even number")
else:
    print("odd number")

